### ISSUE TITLE
changeset, timestamp, version

### ISSUE THREAD

**Issue by pnorman** [osmlab/openstreetmap-json-schema#10]
From Roland Olbricht (@drolbr)

> Another aspect I suggest to consider is that `changeset`, `timestamp`
> and `version` are pretty irrelevant for a couple of use cases so it
> could be helpful to make them optional, too.

**Comment by pnorman** [comment]
Editors absolutely require `version`. If we made it optional, you could send valid osm-json to an editor but it would be impossible for them to edit.

It is possible to edit without `changeset`, `timestamp`, `uid`, and `username` but editors use this information, and we really want users to be able to see what they're editing without an additional call.

**Comment by joto** [comment]
Those are different use cases. So the normal OSM API should definitely always have those fields. But other APIs or downloads or whatever might choose to leave some fields off. I don't see this as a problem, really.

Maybe the document should say something like: Implementations are allowed to make some fields optional, but if they have them they must have the specified meaning.

**Comment by pnorman** [comment]
I think I've added language clarifying the target of the format
