### ISSUE TITLE
Move to a more rigorous definition?

### ISSUE THREAD

**Issue by pnorman** [osmlab/openstreetmap-json-schema#3]
[Some other specifications](https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md#22-the-relationship-data-type) define data types in tables, listing allowable members and member types. This seems a more rigorous way to define a spec than an example document like this, but is it worth it? It probably has advantages if we want to reuse part of one spec in others (e.g. pull an existing definition of nodes into a spec for osmChange)

**Comment by jfirebaugh** [comment]
[JSON schema](http://json-schema.org/) is decent. I wrote schemas for iD preset formats, and now I can run automated validations whenever I make preset changes -- it's working out well.

**Comment by iandees** [comment]
:+1: for jsonschema.

**Comment by pnorman** [comment]
:+1: just need to implement it. Ties nicely into automated validations of cgimap output too - we can actually check that we're producing what we expect.

**Comment by pnorman** [comment]
validator of json against schemas, including schemas against the meta-schema: http://json-schema-validator.herokuapp.com/index.jsp

**Comment by pnorman** [comment]
about 50% done. nodes are done, relations/ways are partially a copy/paste of that.

One concern is that although a schema is very useful for validation and a rigorous definition, it's not the most readable. I'm not sure what the solution is. Have an informative example like what there is right now?

Additionally, there are some constraints that can't be expressed in json schema (e.g. (id,version) being unique among object types)
