### ISSUE TITLE
Should uid/username be required

### ISSUE THREAD

**Issue by pnorman** [osmlab/openstreetmap-json-schema#8]
For anonymous users should we omit uid/username or require them to be present with the value null?

**Comment by tmcw** [comment]
:+1: for null rather than an absent property

**Comment by pnorman** [comment]
cc @drolbr since he expressed opinions on similar issues with different properties

**Comment by pnorman** [comment]
> :+1: for null rather than an absent property

Do you (or anyone) happen to know how to specify a property must be a null or a string with json-schema (#3), short of

``` javascript
"anyOf": [
  {visible node},
  {visible anonymous node},
  {deleted node},
  {deleted anonymous node}
]
```

**Comment by pnorman** [comment]
answer: make user and uid oneOf?
